### ISSUE TITLE
log less scary message when stdin closed

### ISSUE THREAD

**Issue by kurtbrose** [doublereedkurt/ufork#5]
when stdin is closed it isn't a big deal, the REPL just doesn't run, but it looks scary

```python
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/app/.heroku/python/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/ufork/ufork.py", line 497, in _interact
    inp = self.console.raw_input('ufork>> ')
  File "/app/.heroku/python/lib/python2.7/code.py", line 281, in raw_input
    return raw_input(prompt)
EOFError: EOF when reading a line
```

**Comment by jayalane** [comment]
scary but common and unimportant messages definitely discourage adoptation.
